codecov:
  # Tell codecov our default branch.
  branch: main
  # Don't trigger CI failure on coverage reduction.
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true